project:
  type: website
  output-dir: docs
  resources:
    - page-layout/tufte.pdf
# project:
#   type: website
#   output-dir: docs
# execute:
#   freeze: auto
# website:
#   navbar:
#     background: primary
#     search: true
# theme:
#   light: flatly
#   dark: darkly
