scalar Text

type account_upgrade {
  id: String!
  from_address: String!
  created_at: Int!
  created_at_block: Int!
  implementation: String!
}

type account_create {
  id: String!
  from_address: String!
  created_at: Int!
  created_at_block: Int!
}
